import type { CompanyProfile, ResearchProfile, NavyChallenge } from "@/types";

export const sampleCompanies: CompanyProfile[] = [
  {
    id: "comp-1",
    name: "Maritime Robotics BV",
    sector: "Autonomous Systems",
    description: "Maritime Robotics develops autonomous underwater vehicles (AUVs) and unmanned surface vessels (USVs) for naval operations, mine countermeasures, and maritime surveillance. Our modular platform enables rapid deployment for various naval missions including hydrographic survey, environmental monitoring, and threat detection in contested waters.",
    capabilities: ["autonomous navigation", "underwater robotics", "sensor integration", "real-time data processing", "mine countermeasures"],
    technologies: ["ROS2", "sonar systems", "machine learning", "edge computing", "satellite communication"],
    trl_level: 7,
    team_size: "51-200",
    website: "https://example.com/maritime-robotics",
    contact_email: "info@maritime-robotics.example",
    use_cases: ["Mine detection and neutralization", "Port security surveillance", "Underwater infrastructure inspection"],
    quality_score: 92,
    created_at: "2025-11-15T10:00:00Z",
    updated_at: "2025-11-15T10:00:00Z",
  },
  {
    id: "comp-2",
    name: "CyberSea Defense",
    sector: "Cybersecurity",
    description: "CyberSea Defense provides advanced cybersecurity solutions for maritime and naval systems. Specializing in OT/IT security for ship systems, secure communications, and threat intelligence for maritime infrastructure. Our AI-driven threat detection platform monitors network anomalies across fleet-wide deployments.",
    capabilities: ["maritime cybersecurity", "threat detection", "secure communications", "network monitoring", "incident response"],
    technologies: ["AI threat detection", "zero trust architecture", "encrypted communications", "SIEM", "blockchain"],
    trl_level: 8,
    team_size: "11-50",
    contact_email: "contact@cybersea.example",
    use_cases: ["Fleet-wide cyber defense", "Shipboard OT security", "Secure tactical communications"],
    quality_score: 88,
    created_at: "2025-10-20T14:30:00Z",
    updated_at: "2025-10-20T14:30:00Z",
  },
  {
    id: "comp-3",
    name: "DeepSense Analytics",
    sector: "Data Analytics & AI",
    description: "DeepSense Analytics transforms raw maritime sensor data into actionable intelligence. Our deep learning platform processes multi-spectral satellite imagery, AIS data, and acoustic signatures to provide real-time maritime domain awareness. We enable predictive analytics for naval logistics and threat assessment.",
    capabilities: ["data analytics", "satellite imagery analysis", "predictive modeling", "maritime domain awareness", "signal processing"],
    technologies: ["deep learning", "computer vision", "big data", "cloud computing", "GIS"],
    trl_level: 6,
    team_size: "11-50",
    contact_email: "hello@deepsense.example",
    use_cases: ["Maritime domain awareness", "Predictive maintenance for naval vessels", "Intelligence fusion"],
    quality_score: 85,
    created_at: "2025-09-05T09:00:00Z",
    updated_at: "2025-09-05T09:00:00Z",
  },
  {
    id: "comp-4",
    name: "GreenWave Propulsion",
    sector: "Energy & Propulsion",
    description: "GreenWave Propulsion develops next-generation hybrid electric propulsion systems for naval vessels. Our technology reduces fuel consumption by 40% while maintaining operational readiness. Modular battery systems enable silent running capabilities critical for submarine and surface stealth operations.",
    capabilities: ["hybrid propulsion", "battery technology", "power management", "silent running", "energy efficiency"],
    technologies: ["solid-state batteries", "electric motors", "power electronics", "thermal management", "hydrogen fuel cells"],
    trl_level: 5,
    team_size: "11-50",
    contact_email: "info@greenwave.example",
    use_cases: ["Submarine silent propulsion", "Surface vessel fuel reduction", "Shore-to-ship power"],
    quality_score: 80,
    created_at: "2025-08-12T11:15:00Z",
    updated_at: "2025-08-12T11:15:00Z",
  },
];

export const sampleResearch: ResearchProfile[] = [
  {
    id: "res-1",
    title: "Autonomous Swarm Intelligence for Maritime Operations",
    institution: "TU Delft - Maritime Technology",
    principal_investigator: "Prof. Dr. Jan van der Berg",
    field: "Autonomous Systems",
    description: "This research program investigates swarm intelligence algorithms for coordinating multiple autonomous vessels in complex maritime environments. We develop decentralized decision-making frameworks that enable USV/UUV swarms to perform collaborative search, patrol, and surveillance missions without continuous human oversight. Our approach combines bio-inspired algorithms with formal verification methods to ensure safe and predictable swarm behavior in contested waters.",
    keywords: ["swarm intelligence", "autonomous vessels", "decentralized control", "multi-agent systems", "maritime autonomy", "USV", "UUV"],
    publications: ["Swarm-based Mine Countermeasures (IEEE 2025)", "Decentralized Maritime Patrol Algorithms (JMSE 2024)"],
    trl_level: 4,
    funding_status: "EU Horizon funded",
    collaboration_interest: ["industry testing", "naval exercises", "sensor integration", "real-world validation"],
    contact_email: "j.vanderberg@tudelft.example",
    quality_score: 95,
    created_at: "2025-07-01T08:00:00Z",
    updated_at: "2025-07-01T08:00:00Z",
  },
  {
    id: "res-2",
    title: "Quantum-Resistant Cryptography for Naval Communications",
    institution: "TNO Defense & Security",
    principal_investigator: "Dr. Sarah Bakker",
    field: "Cybersecurity",
    description: "This project develops post-quantum cryptographic protocols specifically designed for maritime communication environments. We address the unique challenges of high-latency, low-bandwidth naval communication channels while ensuring quantum-resistant security. Our work includes new key distribution mechanisms for fleet-wide encrypted communications and quantum key distribution over free-space optical links between vessels.",
    keywords: ["post-quantum cryptography", "naval communications", "quantum key distribution", "secure protocols", "maritime security"],
    publications: ["Post-Quantum Naval Comms Framework (ACM CCS 2025)", "QKD for Maritime Environments (Nature Comms 2024)"],
    trl_level: 3,
    funding_status: "Dutch MoD funded",
    collaboration_interest: ["protocol implementation", "field testing", "hardware integration"],
    contact_email: "s.bakker@tno.example",
    quality_score: 91,
    created_at: "2025-06-15T10:00:00Z",
    updated_at: "2025-06-15T10:00:00Z",
  },
  {
    id: "res-3",
    title: "Bio-Inspired Anti-Fouling Coatings for Naval Vessels",
    institution: "Wageningen University - Marine Research",
    principal_investigator: "Prof. Dr. Lisa de Groot",
    field: "Materials Science",
    description: "We develop environmentally sustainable anti-fouling coatings inspired by marine organisms. These bio-mimetic surface treatments prevent biofouling on naval vessel hulls without releasing toxic substances into the marine environment. Our nano-structured surfaces reduce drag by up to 15%, directly improving fuel efficiency and reducing the acoustic signature of vessels.",
    keywords: ["anti-fouling", "bio-inspired coatings", "naval materials", "drag reduction", "marine biology", "nanotechnology"],
    publications: ["Bio-Mimetic Naval Coatings (Advanced Materials 2025)", "Sustainable Anti-Fouling Review (Marine Ecology 2024)"],
    trl_level: 5,
    funding_status: "NWO funded",
    collaboration_interest: ["coating application testing", "long-term sea trials", "industrial scale-up"],
    contact_email: "l.degroot@wur.example",
    quality_score: 87,
    created_at: "2025-05-20T09:30:00Z",
    updated_at: "2025-05-20T09:30:00Z",
  },
];

export const sampleChallenges: NavyChallenge[] = [
  {
    id: "chal-1",
    title: "Autonomous Mine Countermeasures in Shallow Waters",
    classification: "unclassified",
    domain: "Mine Warfare",
    description: "The Belgian Navy requires an autonomous solution for detecting and classifying sea mines in shallow coastal waters (depth 5-50m). Current mine countermeasure operations are time-intensive and put personnel at risk. We seek solutions that can autonomously survey designated areas, detect potential mines using multiple sensor modalities, classify threats with high confidence, and report findings in real-time to command centers.",
    operational_context: "Operations in the North Sea and Belgian coastal zones with strong currents, poor visibility, and mixed seabed composition. Systems must operate in Sea State 3 conditions and integrate with existing NATO mine warfare doctrine and communication standards.",
    requirements: ["autonomous operation for 8+ hours", "multi-sensor detection (sonar, magnetic, optical)", "real-time classification with >95% accuracy", "NATO STANAG compliant communications", "deployable from existing vessels"],
    desired_trl: 6,
    timeline: "18 months",
    priority: "high",
    status: "open",
    tags: ["autonomous systems", "mine warfare", "underwater robotics", "sonar", "classification", "shallow water"],
    quality_score: 94,
    created_at: "2025-12-01T08:00:00Z",
    updated_at: "2025-12-01T08:00:00Z",
  },
  {
    id: "chal-2",
    title: "Cyber Resilience for Next-Generation Combat Management Systems",
    classification: "unclassified",
    domain: "Cyber Defense",
    description: "As combat management systems become increasingly networked and software-defined, the attack surface for cyber threats grows significantly. We need innovative approaches to ensure cyber resilience of shipboard combat systems. Solutions should enable continuous monitoring, automatic threat response, and rapid recovery from cyber incidents without degrading combat capability.",
    operational_context: "Modern frigates and patrol vessels operating in contested electromagnetic environments. Systems must handle sophisticated state-sponsored cyber attacks while maintaining real-time combat system performance. Integration with existing SEWACO systems is essential.",
    requirements: ["zero-trust architecture for combat systems", "real-time anomaly detection", "automated incident response", "minimal latency impact on combat operations", "air-gapped backup capability"],
    desired_trl: 7,
    timeline: "12 months",
    priority: "critical",
    status: "open",
    tags: ["cybersecurity", "combat systems", "threat detection", "zero trust", "maritime security", "resilience"],
    quality_score: 96,
    created_at: "2025-11-15T10:30:00Z",
    updated_at: "2025-11-15T10:30:00Z",
  },
  {
    id: "chal-3",
    title: "Sustainable Energy Solutions for Forward Operating Bases",
    classification: "unclassified",
    domain: "Logistics & Sustainment",
    description: "Naval forward operating bases and expeditionary camps require reliable energy that reduces logistic dependency on fuel supply chains. We seek hybrid energy solutions combining renewable sources with advanced energy storage that can provide reliable power in remote maritime and coastal environments while reducing the acoustic and thermal signature of installations.",
    operational_context: "Caribbean and Mediterranean operational areas. Bases may operate for weeks without resupply. Tropical to temperate conditions, salt air environment. Power requirements range from 50kW to 500kW depending on base size.",
    requirements: ["hybrid renewable energy generation", "energy storage for 72-hour autonomy", "salt-air corrosion resistant", "transportable by standard military logistics", "reduced thermal and acoustic signature"],
    desired_trl: 5,
    timeline: "24 months",
    priority: "medium",
    status: "open",
    tags: ["energy", "sustainability", "battery storage", "renewable", "logistics", "forward base"],
    quality_score: 89,
    created_at: "2025-10-10T14:00:00Z",
    updated_at: "2025-10-10T14:00:00Z",
  },
];
