import type { Proposal } from "@/types";

export const sampleProposals: Proposal[] = [
  {
    id: "prop-1",
    title: "AI-Powered Mine Detection Swarm System",
    submitter_name: "Maritime Robotics BV",
    submitter_org: "Maritime Robotics BV",
    description:
      "Proposal to deploy a coordinated swarm of autonomous underwater vehicles equipped with AI-driven sonar classification for mine countermeasures in shallow coastal waters. The system uses decentralized swarm intelligence to cover large areas efficiently while maintaining high detection accuracy. Each vehicle carries multi-spectral sensors and can communicate findings in real-time to a command vessel.",
    domain: "Mine Warfare",
    challenge_id: "chal-1",
    company_id: "comp-1",
    status: "approved",
    votes: [
      { id: "v1", voter_name: "Cdr. de Vries", voter_role: "Naval Officer", interested: true, comment: "Strong operational fit for current MCM gaps", created_at: "2026-01-10T09:00:00Z" },
      { id: "v2", voter_name: "Lt. Bakker", voter_role: "Procurement", interested: true, comment: "Competitive pricing and proven track record", created_at: "2026-01-10T10:30:00Z" },
      { id: "v3", voter_name: "Dr. Jansen", voter_role: "Innovation Manager", interested: true, created_at: "2026-01-10T11:00:00Z" },
      { id: "v4", voter_name: "Maj. Smit", voter_role: "Operations", interested: false, comment: "Concerned about integration with existing fleet", created_at: "2026-01-10T14:00:00Z" },
    ],
    assessment: {
      strategic_fit: 90,
      unmet_need: 85,
      feasibility: 80,
      innovative: 88,
      total_score: 86,
      assessor_name: "Innovation Assessment Board",
      assessor_notes: "Strong alignment with Belgian Navy MCM modernization priorities. Technology demonstrated at TRL 7.",
      created_at: "2026-01-15T10:00:00Z",
    },
    professor_review: {
      reviewer_name: "Prof. Dr. Jan van der Berg",
      institution: "TU Delft",
      state_of_the_art_summary: "Current swarm-based MCM systems are in early research stages globally. This proposal represents a significant advancement over existing single-vehicle approaches. The decentralized architecture is novel in the maritime mine warfare domain.",
      novelty_assessment: "highly_novel",
      recommendation: "proceed",
      comments: "Recommend proceeding with field trials. The swarm coordination algorithms show promise beyond current NATO state-of-the-art.",
      created_at: "2026-01-20T14:00:00Z",
    },
    meetup_scheduled: "2026-02-15T10:00:00Z",
    created_at: "2026-01-05T08:00:00Z",
    updated_at: "2026-02-01T10:00:00Z",
  },
  {
    id: "prop-2",
    title: "Zero-Trust Cyber Shield for Combat Management",
    submitter_name: "CyberSea Defense",
    submitter_org: "CyberSea Defense",
    description:
      "Implementation of a comprehensive zero-trust security architecture for next-generation combat management systems. The solution provides continuous monitoring, AI-driven threat detection, and automated incident response capabilities while maintaining sub-millisecond latency for combat operations. Includes air-gapped backup and rapid recovery mechanisms.",
    domain: "Cyber Defense",
    challenge_id: "chal-2",
    company_id: "comp-2",
    status: "discussion",
    votes: [
      { id: "v5", voter_name: "Cdr. de Vries", voter_role: "Naval Officer", interested: true, comment: "Critical capability gap", created_at: "2026-01-12T09:00:00Z" },
      { id: "v6", voter_name: "Lt. Bakker", voter_role: "Procurement", interested: true, created_at: "2026-01-12T10:00:00Z" },
      { id: "v7", voter_name: "Dr. Jansen", voter_role: "Innovation Manager", interested: false, comment: "Need more evidence of combat-system integration", created_at: "2026-01-12T11:30:00Z" },
    ],
    assessment: {
      strategic_fit: 85,
      unmet_need: 90,
      feasibility: 55,
      innovative: 70,
      total_score: 72,
      assessor_name: "Innovation Assessment Board",
      assessor_notes: "High strategic value but feasibility concerns around integration with legacy SEWACO systems. Score falls in discussion range.",
      created_at: "2026-01-18T10:00:00Z",
    },
    created_at: "2026-01-08T08:00:00Z",
    updated_at: "2026-01-18T10:00:00Z",
  },
  {
    id: "prop-3",
    title: "Hybrid Energy Microgrid for Forward Bases",
    submitter_name: "GreenWave Propulsion",
    submitter_org: "GreenWave Propulsion",
    description:
      "Modular hybrid energy system combining solar arrays, wind turbines, and solid-state battery storage for naval forward operating bases. The system is containerized for standard military logistics and provides 72-hour autonomous operation. Integrated thermal management reduces heat signature while salt-air resistant components ensure reliability in maritime environments.",
    domain: "Logistics & Sustainment",
    challenge_id: "chal-3",
    company_id: "comp-4",
    status: "sniff_assessment",
    votes: [
      { id: "v8", voter_name: "Cdr. de Vries", voter_role: "Naval Officer", interested: true, created_at: "2026-02-01T09:00:00Z" },
      { id: "v9", voter_name: "Lt. Bakker", voter_role: "Procurement", interested: true, comment: "Good cost-benefit potential", created_at: "2026-02-01T10:00:00Z" },
      { id: "v10", voter_name: "Maj. Smit", voter_role: "Operations", interested: true, comment: "Aligns with sustainability goals", created_at: "2026-02-01T14:00:00Z" },
    ],
    created_at: "2026-01-25T08:00:00Z",
    updated_at: "2026-02-05T10:00:00Z",
  },
  {
    id: "prop-4",
    title: "Quantum-Safe Naval Communication Protocol",
    submitter_name: "TNO Defense & Security",
    submitter_org: "TNO Defense & Security",
    description:
      "Post-quantum cryptographic protocol suite designed for high-latency maritime communication channels. Includes quantum key distribution over free-space optical links between vessels and a hybrid classical/quantum encryption approach for backwards compatibility with existing NATO communication standards.",
    domain: "Cyber Defense",
    status: "voting",
    votes: [
      { id: "v11", voter_name: "Cdr. de Vries", voter_role: "Naval Officer", interested: true, comment: "Future-proofing is essential", created_at: "2026-02-20T09:00:00Z" },
    ],
    created_at: "2026-02-15T08:00:00Z",
    updated_at: "2026-02-20T10:00:00Z",
  },
  {
    id: "prop-5",
    title: "Predictive Maritime Domain Awareness Platform",
    submitter_name: "DeepSense Analytics",
    submitter_org: "DeepSense Analytics",
    description:
      "AI-powered platform combining satellite imagery, AIS data, and acoustic sensor networks for predictive maritime domain awareness. Uses deep learning to identify patterns, predict vessel movements, and detect anomalous behavior in near real-time. Provides a common operational picture with threat probability overlays.",
    domain: "Intelligence & Surveillance",
    company_id: "comp-3",
    status: "rejected",
    votes: [
      { id: "v12", voter_name: "Dr. Jansen", voter_role: "Innovation Manager", interested: false, comment: "Similar capability already being developed in-house", created_at: "2026-02-05T10:00:00Z" },
      { id: "v13", voter_name: "Maj. Smit", voter_role: "Operations", interested: false, comment: "Overlaps with existing NATO MDA systems", created_at: "2026-02-05T14:00:00Z" },
    ],
    assessment: {
      strategic_fit: 50,
      unmet_need: 40,
      feasibility: 75,
      innovative: 60,
      total_score: 55,
      assessor_name: "Innovation Assessment Board",
      assessor_notes: "While technically capable, the solution overlaps significantly with existing MDA capabilities. Does not meet the unmet need threshold.",
      created_at: "2026-02-10T10:00:00Z",
    },
    created_at: "2026-02-01T08:00:00Z",
    updated_at: "2026-02-10T10:00:00Z",
  },
];
